version: '3'
 
services:

  mysql:
    image: mysql:5.7
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_password
      MYSQL_DATABASE: helloworld
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3306:3306"
#    volumes:
#      - dbdata:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: pma-container
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80
#volumes:
#  dbdata: